Modificando o log para a utilização de models e limpeza de codigos nã…
lucianahb/teamolist pull request #14
Opened 2021-01-12 21:33 UTC by Marcellort

Depois de um quase infarto agora sim o PR certo

2021-01-12 22:28 UTC, anapaula-nestor approved these changes

2021-01-13 12:34 UTC, lucianahb approved these changes

2021-01-13 12:53 UTC, lucasljoliveira-olist requested changes

2021-01-13 12:53 UTC, lucasljoliveira-olist commented on backend/models/log.py
> +        self.datetime = datetime
Acho que aqui poderia deixar opcional o datetime tbm, que poderia ser adicionado só na hr de inserir no banco, assim n precisa importar o datetime em todos os outros arquivos, o que vc acha?

2021-01-13 12:53 UTC, lucasljoliveira-olist commented on backend/controller/seller.py
>      write_log('Listed Seller', operation_type)
Não tem que mudar isso aqui ja que mudou a forma de fazer?

2021-01-13 12:55 UTC, Marcellort commented on backend/models/log.py
> +        self.datetime = datetime
eu fiz assim no meu mas o deles não esta com o timestamp íamos ter que alterar a tabela por isso deixei assim

2021-01-13 12:55 UTC, Marcellort commented on backend/controller/seller.py
>      write_log('Listed Seller', operation_type)
deixei passar sry vou concertar agora

2021-01-13 13:34 UTC, lucasljoliveira-olist approved these changes

2021-01-13 13:34 UTC, lucasljoliveira-olist commented on backend/models/log.py
> +        self.datetime = datetime
Lá no create da tabela eu coloquei o campo como timestamp, não acha valido colocar?

2021-01-13 13:37 UTC, merged